master:
  datasource:
    url: jdbc:mysql://210.47.16.56/db_ezhaohui?useSSL=false&serverTimezone=UTC&charactorEncoding=UTF-8
    username: root
    password: Join666!
    driverClassName: com.mysql.cj.jdbc.Driver

spring:
  profiles:
    active: dev
  application:
    name: ezhaohui
  resources:
    static-locations: classpath:/resources/,classpath:/static/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


server:
  port: 8080

mybatis:
  type-aliases-package: com.join.ezhaohui.entity